### ISSUE TITLE
Closing the yellow "in beta" notifications while map hasn't loaded fully redirects to landing page

### ISSUE THREAD

**Issue by Bubblbu** [OpenKnowledgeMaps/Headstart#185] opened 2018-02-20 19:36 UTC

**Comment by pkraker** [comment] 2018-02-21 23:25
Couldn't reproduce this bug. Which OS/browser did you test this with?

**Comment by pkraker** [comment] 2019-11-19 10:59
This was an issue with the project website rather than Headstart. It has been fixed now, see OpenKnowledgeMaps/project-website#33

**Closed by pkraker** 2019-11-19 10:59 UTC
Labels: bug, frontend
